### ISSUE TITLE
Add notebook tutorials for newly added truth/light-curve info

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-data-portal#89]
This is a sub-issue of #88.

**Comment by yymao** [comment]
According to the meeting note, these are what we need to include in the tutorial:

1. How to do a search on RA/Dec to match to truth summary catalog, object catalog
2. How to do a light curve

**Comment by JoanneBogart** [comment]
The notebook fails to load catalog desc_dc2_run2.2i_truth_sn_summary because the catalog specifies filename pattern as `dc2_run2.2i_truth_sn_summary_v1-0-0.parquet` and the file under gsharing is
`truth_sn_summary_v1-0.0.parquet`
It looks like the catalog is wrong.    This is a problem I think I fixed for the star catalogs but apparently not for sn.
I'll make a quick pull request in GCRCatalogs to fix it.

**Comment by yymao** [comment]
Yes, I've opened a draft PR in gcr-catalogs already.
